services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registration_api_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web_v1:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000 -P /rails/tmp/pids/server_v1.pid
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      RAILS_ENV: development
      REGISTRATION_API_VERSION: v1
    ports:
      - "3001:3000"
    volumes:
      - .:/rails
    depends_on:
      - db

  web_v2:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000 -P /rails/tmp/pids/server_v2.pid
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      RAILS_ENV: development
      REGISTRATION_API_VERSION: v2
    ports:
      - "3002:3000"
    volumes:
      - .:/rails
    depends_on:
      - db

  web_v3:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000 -P /rails/tmp/pids/server_v3.pid
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      RAILS_ENV: development
      REGISTRATION_API_VERSION: v3
    ports:
      - "3003:3000"
    volumes:
      - .:/rails
    depends_on:
      - db

volumes:
  postgres_data:
